arrowParens: "avoid"
bracketSpacing: true
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.18"
      tabWidth: 4
